project/urls.py
from django.conf.urls.defaults import *
from project import views

urlpatterns = patterns('',
    (r'^(?P<year>\d{4})/$', views.projects_by_year),
    (r'^(?P<year>\d{4})/(?P<code>\w{6})/$', views.project_detail),
)

projects/urls.py
from django.conf.urls.defaults import *
#from projects import views
 
urlpatterns = patterns('projects.views',
    url(
        r'^$',
        'projects_main',
        name='projects_main'
    ),
    url(
        r'^(?P<year>\d{4})/$',
        'projects_by_year',
        name='projects_by_year'
    ),
    url(
        r'^(?P<year>\d{4})/(?P<category>[A-Z]{3})/$',
        'project_by_year_and_category',
        name='projects_project_by_year_and_category'
    ),
    url(
        r'^(?P<category>[A-Z]{3})/$',
       'projects_by_category',
        name='projects_by_category'
    ),
    url(
        r'^(?P<year>\d{4})/(?P<category>[A-Z]{3})/(?P<code>\d{3})/$',
        'project_detail',
        name='projects_project_detail'
    ),
    url(
        r'^slug/(?P<slug>[a-z0-9-_]+)/$',
        'project_detail',
        name='projects_project_detail_slug'
    ),
    url(
        r'^favorites/(?P<username>\w+)/$',
        'favorite_projects',
        name='projects_favorite_projects'
    ),
    url(
        r'^favorites/add/(?P<year>\d{4})/(?P<category>[A-Z]{3})/(?P<code>\d{3})/$',
        'add_favorite',
        name='projects_add_favorite',
    ),
    url(
        r'^favorites/remove/(?P<year>\d{4})/(?P<category>[A-Z]{3})/(?P<code>\d{3})/$',
        'remove_favorite',
        name='projects_remove_favorite',
    ),
    url(
        r'^favorites/add/(?P<slug>[a-z0-9-_]+)/$',
        'add_favorite',
        name='projects_add_favorite_slug',
    ),
    url(
        r'^favorites/remove/(?P<slug>[a-z0-9-_]+)/$',
        'remove_favorite',
        name='projects_remove_favorite_slug',
    ),
)
urlpatterns += patterns('projects.views',
    url(
        r'^request/$',
        'request_project',
        name='projects_request_project'
    ),
    url(
        r'^new/$',
        'new_project',
        name='projects_new_project'
    ),
#    url(
#        r'^slug/(?P<slug>[a-z0-9-_]+)/edit/$',
#        'edit_project',
#        name='projects_edit_project'
#    ),
#    url(
#        r'^(?P<year>\d{4})/(?P<category>[A-Z]{3})/(?P<code>\d{3})/edit/$',
#        'edit_project',
#        name='projects_edit_project'
#    ),
)

tagging/urls.py
from django.conf.urls.defaults import *
from projects.models import Project
from tagging.models import Tag

urlpatterns = patterns('',
    url(
        r'^$',
        'django.views.generic.list_detail.object_list',
        { 'queryset': Tag.objects.all() }
    ),
    url(
        r'^(?P<tag>[-\w\s]+)/$',
        'tagging.views.tag_detail',
        name = 'tagging_tag_detail',
    ),
    url(
        r'^projects/(?P<tag>[-\w]+)/$',
        'tagging.views.tagged_object_list',
        { 'queryset_or_model': Project,
        'template_name': 'projects/projects_by_tag.html' }
    ),
)

urls.py
# -*- coding: utf-8 -*-
from django.conf.urls.defaults import *
from django.conf import settings

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    (r'^admin/doc/', include('django.contrib.admindocs.urls')),
    (r'^admin/(.*)', admin.site.root),
    (r'^accounts/', include('registration.urls')),
    (r'^articles/', include('articles.urls')),
    (r'^blog/', include('blog.urls')),
    (r'^comments/', include('django.contrib.comments.urls')),
    (r'^friends/', include('friends.urls')),
    (r'^institutions/', include('institutions.urls')),
    (r'^profiles/', include('profiles.urls')),
    (r'^projects/', include('projects.urls')),
    (r'^search/', include('search.urls')),
    (r'^tags/', include('tagging.urls')),
    (r'^messages/', include('messages.urls')),
    (r'^photologue/', include('photologue.urls')),
    (r'^stats/', include('status.urls')),
    (r'^$', include('home.urls')),
    (r'^media/(.*)$', 'django.views.static.serve',
     {'document_root': settings.MEDIA_ROOT}),
)

project/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.contrib.auth.models import User
from django.contrib import admin

CATEGORIES = (
        ('AGR', 'Ciências Agrárias'),
        ('BIO', 'Ciências Biológicas'),
        ('ENG', 'Engenharias'),
        ('EXA', 'Ciências Exatas e da Terra'),
        ('HUM', 'Ciências Humanas'),
        ('SAU', 'Ciências da Saúde'),
        ('SOC', 'Ciências Sociais Aplicadas'),
)

class Project(models.Model):
    name = models.CharField(max_length=200)
    abstract = models.TextField()
    students = models.ManyToManyField(User, related_name='students')
    advisors = models.ManyToManyField(User, related_name='advisors')
    institution = models.CharField(max_length=100)
    category = models.CharField(max_length=3, choices=CATEGORIES)
    #subcategory = models.CharField(max_length=50)
    keywords = models.CharField(max_length=100)

    edition = models.IntegerField()
    code = models.CharField(max_length=6)

    video = models.CharField(max_length=47)

    def __unicode__(self):
        return self.name

    @models.permalink
    def get_absolute_url(self):
        return ('project.views.project_detail', (), {'year': self.edition, 'code': self.code})

admin.site.register(Project)

projects/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime
from tagging.fields import TagField
from institutions.models import Institution
from profiles.models import UserProfile

CATEGORIES = (
        (u'AGR', u'Ciências Agrárias'),
        (u'BIO', u'Ciências Biológicas'),
        (u'ENG', u'Engenharias'),
        (u'EXA', u'Ciências Exatas e da Terra'),
        (u'HUM', u'Ciências Humanas'),
        (u'SAU', u'Ciências da Saúde'),
        (u'SOC', u'Ciências Sociais Aplicadas'),
)

class Project(models.Model):
    slug = models.SlugField(unique=True, null=True, blank=True, verbose_name='Slug')
    name = models.CharField(max_length=255, blank=True, verbose_name='Nome')
    abstract = models.TextField(blank=True, verbose_name='Resumo')
    students = models.ManyToManyField(UserProfile, related_name='students', verbose_name='Estudantes')
    advisors = models.ManyToManyField(UserProfile, related_name='advisors', verbose_name='Orientadores')
    institution = models.ForeignKey(Institution, blank=True, null=True, verbose_name='Instituição')
    keywords = TagField(verbose_name='Palavras-chave')

    category = models.CharField(max_length=3, choices=CATEGORIES, blank=True, null=True, verbose_name='Categoria')
    edition = models.CharField(max_length=4, null=True, verbose_name='Ano')
    code = models.CharField(max_length=3, null=True, verbose_name='Código')

    video = models.CharField(max_length=47, blank=True, verbose_name='Vídeo')
    is_local = models.BooleanField(default=True, verbose_name='Local?')

    def __unicode__(self):
        return self.name

    class Meta:
        unique_together = (('category', 'edition', 'code'),)
        verbose_name='Projeto'

    @models.permalink
    def get_absolute_url(self):
        if self.slug:
            return ('projects_project_detail_slug', (), {'slug': self.slug})
        else:
            return ('projects_project_detail', (), {'year': self.edition,
                                                    'category': self.category,
                                                    'code': self.code})
            

class Prize(models.Model):
    name = models.CharField(max_length=100, unique=True, verbose_name='Nome')
    institution = models.ForeignKey(Institution, verbose_name='Instituição')
    description = models.TextField(blank=True, verbose_name='Descrição')

    def __unicode__(self):
        return self.name

    class Meta:
        verbose_name='Prêmio'

class ProjectLink(models.Model):
    user = models.ForeignKey(User, verbose_name='Usuário')
    project = models.ForeignKey(Project, verbose_name='Projeto')
    date_added = models.DateTimeField(default=datetime.now, verbose_name='Data de Adição')

    def __unicode__(self):
        return u'%s é favorito de %s' % (self.project.name, self.user.username)

    class Meta:
        unique_together = (('user', 'project'),)
        verbose_name='Projeto Favorito'
        verbose_name_plural='Projetos Favoritos'

class PrizeLink(models.Model):
    prize = models.ForeignKey(Prize, verbose_name='Prêmio')
    project = models.ForeignKey(Project, verbose_name='Projeto')
    date_added = models.DateTimeField(default=datetime.now, verbose_name='Data de Adição')

    def __unicode__(self):
        return u'%s recebeu o prêmio de %s' % (self.project.name, self.prize.name)

    class Meta:
        verbose_name='Projeto com prêmio'
        verbose_name_plural='Projetos com prêmios'

projects/forms.py
from django import forms
from projects.models import Project

ROLES = (
    (u'E', u'Estudante'),
    (u'O', u'Orientador'),
)

class ProjectForm(forms.ModelForm):
    slug = forms.SlugField(required=True)
    role = forms.CharField(required=True, widget=forms.Select(choices=ROLES))

    class Meta:
        model = Project
        exclude = ('students','advisors','edition','code','video','is_local',)

project/views.py
# -*- coding: utf-8 -*-
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render_to_response
from django.template import RequestContext

from project.models import Project

def projects_by_year(request, year):
    project_list = Project.objects.filter(edition=year)
    return render_to_response('project/year_list.html',
                              {'project_list': project_list},
                              context_instance = RequestContext(request))

def project_detail(request, year, code):
    pj = get_object_or_404(Project, edition=year, code=code)
    return render_to_response('project/project_detail.html',
                              {'project': pj},
                              context_instance = RequestContext(request))

projects/views.py
from django.views.generic import list_detail
from django.shortcuts import get_object_or_404, render_to_response, redirect
from django.template import RequestContext
from django.http import Http404, HttpResponseRedirect
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required

from projects.models import Project, ProjectLink, CATEGORIES
from projects.utils import get_favorite_projects, is_favorite, get_prizes
from projects.forms import ProjectForm

def projects_main(request):
    years = range(2003,2010)
    categories = list(CATEGORIES)
    return render_to_response('projects/projects_main.html',
                              {'years': years,
                               'categories': categories},
                              context_instance = RequestContext(request))

def projects_by_year(request, year):
    if (int(year) < 2003 or int(year) > 2009):
        raise Http404
    else:
        return list_detail.object_list(
                   request,
                   queryset = Project.objects.filter(edition=year),
                   template_object_name = 'project',
                   extra_context = {'title': year, 'year': year}
               )

def project_by_year_and_category(request, year, category):
    if (int(year) < 2003 or int(year) > 2009):
        raise Http404
    categories = dict(CATEGORIES)
    if (category not in categories.keys()):
        raise Http404
    else:
        return list_detail.object_list(
           request,
           queryset = Project.objects.filter(category=category, edition=year),
           template_object_name = 'project',
           extra_context = {'title': year + " | " +categories[category],
                            'year': year,
                            'category': category
                            }
       )

def projects_by_category(request, category):
    categories = dict(CATEGORIES)
    if (category not in categories.keys()):
        raise Http404
    else:
        return list_detail.object_list(
                   request,
                   queryset = Project.objects.filter(category=category),
                   template_object_name = 'project',
                   extra_context = {'title': categories[category]}
               )

def project_detail(request, year=None, category=None, code=None, slug=None):
    if slug:
        project = get_object_or_404(Project, slug=slug)
    else:
        project = get_object_or_404(Project, edition=year, category=category, code=code)

    visitor = request.user
    student_list = project.students.all()
    advisor_list = project.advisors.all()
    prize_list   = get_prizes(project)

    if visitor.is_authenticated():
        is_fav = is_favorite(visitor, project)
        is_owner = visitor.get_profile() in ( list(student_list)+list(advisor_list) )
    else:
        is_fav = is_owner = False

    return render_to_response('projects/project_detail.html',
                              { 'project': project,
                                'is_favorite': is_fav,
                                'is_owner': is_owner,
                                'student_list': student_list,
                                'advisor_list': advisor_list,
                                'prize_list': prize_list,
                                'title': project.name,
                                'year': project.edition,
                                'category': project.category,
                                'code': project.code,
                              },
                              context_instance=RequestContext(request))

@login_required
def favorite_projects(request, username):
    user = get_object_or_404(User, username=username)
    return list_detail.object_list(
                request,
                queryset = get_favorite_projects(user),
                template_object_name = 'project',
                extra_context = {'title': username},
            )

@login_required
def add_favorite(request, year=None, category=None, code=None, slug=None):
    visitor = request.user
    if slug:    
        project = get_object_or_404(Project, slug=slug)
    else:
        project = get_object_or_404(Project, edition=year, category=category, code=code)
    ProjectLink.objects.get_or_create(user=visitor, project=project)
    return redirect(project)

@login_required
def remove_favorite(request, year=None, category=None, code=None, slug=None):
    visitor = request.user
    if slug:    
        project = get_object_or_404(Project, slug=slug)
    else:
        project = get_object_or_404(Project, edition=year, category=category, code=code)
    ProjectLink.objects.get(user=visitor, project=project).delete()
    return redirect(project)

@login_required
def request_project(request):
    return render_to_response('projects/request_project.html',
                              {'visitor': request.user.get_profile() },
                              context_instance = RequestContext(request))

@login_required
def new_project(request):
    if request.method == 'POST':
        form = ProjectForm(data=request.POST, files=request.FILES)
        if form.is_valid():
            project = form.save()
            if request.POST.get("role") == "O": 
                project.advisors.add(request.user.get_profile())
            if request.POST.get("role") == "E":
                project.students.add(request.user.get_profile())
            project.save()
            return HttpResponseRedirect(project.get_absolute_url())
    else:
        form = ProjectForm()  
    return render_to_response('projects/new_project.html',
                              {'form': form},
                              context_instance = RequestContext(request))

templates/projects/base.html
{% extends "base.html" %}

{% block title%} | Projetos | {{ title }}{% endblock %}

{% block header%}
    Projetos | 
{% endblock %}

{% block breadcrumbs%}
<h4>
    {% if code %}
        <a href='../../../'>Projetos</a> >
        <a href='../../'>{{ year }}</a> >
        <a href='../'>{{ category }}</a> >
        {{ code }}
    {% else %}
        {% if category %}
            <a href='../../'>Projetos</a> >
            <a href='../'>{{ year }}</a> >
            {{ category }}
        {% else %}
            {% if year %}
                <a href='../'>Projetos</a> >
                {{ year }}
            {% endif %}
        {% endif %}
    {% endif %}
</h4>
{% endblock %}

templates/projects/new_project.html
{% extends "base.html" %}

{% block title%} | Criar Projeto{% endblock %}

{% block header%}
    <h1>Criar Projeto</h1>
{% endblock %}

{% block content %}

    {% if form.errors %}
        <p style="color: red;">
            Por favor, corrija o{{ user_form.errors|pluralize }} erro{{ user_form.errors|pluralize }} abaixo.
        </p>
        <br>
    {% endif %}

    <form enctype="multipart/form-data" method="post" action="">
        <div class="field">
            <label for="id_slug"><h2>Slug</h2></label>
            {{ form.slug }} {{ form.slug.errors }}
        </div>
        <br>
        <div class="field">
            <label for="id_name"><h2>Nome</h2></label>
            {{ form.name }} {{ form.name.errors }}
        </div>
        <br>
        <div class="field">
            <label for="id_abstract"><h2>Resumo</h2></label>
            {{ form.abstract }} {{ form.abstract.errors }}
        </div>
        <br>
        <div class="field">
            <label for="id_institution"><h2>Instituição</h2></label>
            {{ form.institution }} {{ form.institution.errors }}
        </div>
        <br>
        <div class="field">
            <label for="id_keywords"><h2>Palavras-chave</h2></label>
            {{ form.keywords }} {{ form.keywords.errors }}
        </div>
        <br>
        <div class="field">
            <label for="id_category"><h2>Categoria</h2></label>
            {{ form.category }} {{ form.category.errors }}
        </div>
        <br>
        <div class="field">
            <label for="id_role"><h2>Papel</h2></label>
            {{ form.role }} {{ form.role.errors }}
        </div>
        <br>
        <input type="submit" value="Enviar">
    </form>
{% endblock %}

templates/projects/project_detail.html
{% extends "projects/base.html" %}

{% block header%}
    <h1>{{ title }}</h1> 
{% endblock %}

{% block toolbar %}
    {% if user.is_authenticated %}
        <div id="toolbar">
            {% if is_favorite %}
                <div id="contact_switch" class="toolbar_item">
                    {% if project.slug %}
                        <a href={% url projects_remove_favorite_slug project.slug %}>
                            <img src="{{ MEDIA_URL }}images/toolbar_remove.png" id="toolbar_add" alt="contact" /><br />
                            Remover
                        </a>
                    {% else %}
                        <a href={% url projects_remove_favorite project.edition project.category project.code %}>
                            <img src="{{ MEDIA_URL }}images/toolbar_remove.png" id="toolbar_add" alt="contact" /><br />
                            Remover
                        </a>
                    {% endif %}
                </div>
            {% else %}
                <div id="contact_switch" class="toolbar_item">
                    {% if project.slug %}
                        <a href={% url projects_add_favorite_slug project.slug %}>
                            <img src="{{ MEDIA_URL }}images/toolbar_add.png" id="toolbar_add" alt="contact" /><br />
                            Adicionar
                        </a>
                    {% else %}
                        <a href={% url projects_add_favorite project.edition project.category project.code %}>
                            <img src="{{ MEDIA_URL }}images/toolbar_add.png" id="toolbar_add" alt="contact" /><br />
                            Adicionar
                        </a>
                    {% endif %}
                </div>
            {% endif %}
        </div>
    {% endif %}
{% endblock %}

{% block content %}
    <div class="column" id="column1A">

        <div class="softcorners2" style="background:#f1f2e8;">
            <div class="sosoft" style="background: url('{{ MEDIA_URL }}images/rounder_right_superior.gif') no-repeat top right; height: 15px;">
                <div style="background: url('{{ MEDIA_URL }}images/rounder_left_superior.gif') no-repeat top left;  height: 15px;" ></div>
            </div>
        </div>
        <div class="portrait_area">
            <div class="portrait">
                {% if project.video %}
                    {% if project.is_local %}
                        <video src="{{ MEDIA_URL }}/video/{{ project.video }}"
                        controls="true" width="300" height="288"></video>
                    {% else %}
                        <embed TYPE='application/x-mplayer2'
                        pluginspage='html://www.microsoft.com/windows95/downloads/contents/wurecommended/s_wufeatured/mediaplayer/default.asp'
                        SRC='http://iptv.usp.br/overmedia/Id.do?instance=0&id={{ project.video }}&type=video'
                        ShowControls=1 ShowDisplay=0 ShowStatusBar=1 width=352 height=288 LOOP='false'>
                        </embed> <br/>
                    {% endif %}
                {% endif %}
            </div>
        </div>

        <div class="softcorners2" style="background:#f1f2e8;">
            <div class="sosoft" style=" height: 15px;">
                <div style=" height: 15px;"></div>
            </div>
            <div class="insides">
                <div class="personal">
                    {% if project.slug %}
                        {% if is_owner %}
                            <a href={% url blog_add_post_slug project_slug=project.slug %}>Adicionar post no Diário de Bordo</a><br/>
                        {% endif %}
                    {% else %}
                        {% if is_owner %}
                            <a href={% url blog_add_post edition=project.edition category=project.category code=project.code %}>Adicionar post no Diário de Bordo</a><br/>
                            <a href={% url pl-add-photo edition=project.edition category=project.category code=project.code %}>Adicionar foto na Galeria</a><br/>
                        {% endif %}
                    {% endif %}
                </div>
            </div>
            <div class="sosoft" style="background: url('{{ MEDIA_URL }}images/rounder_right_inferior.gif') no-repeat bottom right; height: 15px;">
                <div style="background: url('{{ MEDIA_URL }}images/rounder_left_inferior.gif') no-repeat bottom left;  height: 15px;" ></div>
            </div>
        </div>
    </div>

	<div class="column" id="columnB">
        <div class="columnBhead">
            <h2>Dados do projeto</h2>
		    <div class="clear">&nbsp;</div>
            <h3>Autor{{ student_list|pluralize:"es" }}</h3>
                {% for student in student_list %}
                   {% if student.is_active %}
                       <a href={{ student.get_absolute_url }}>{{ student.name }}{% if not forloop.last %}, {% endif %}</a>
                   {% else %}
                       {{ student.name }}{% if not forloop.last %}, {% endif %}
                   {% endif %}
                {% endfor %}
                <br/>
                <h3>Orientador{{ advisor_list|pluralize:"es" }}</h3>
                {% for advisor in advisor_list %}
                   {% if advisor.is_active %}
                       <a href={{ advisor.get_absolute_url }}>{{ advisor.name }}{% if not forloop.last %}, {% endif %}</a>
                   {% else %}
                       {{ advisor.name }}{% if not forloop.last %}, {% endif %}
                   {% endif %}
                {% endfor %} 
                <br/>
                <h3>Instituição</h3>
		        <a href={{ project.institution.get_absolute_url }}>{{ project.institution }}</a>
                <br/>
                {% load tagging_tags %}
                {% tags_for_object project as tag_list %}
                {% if tag_list %}
                    <h3>Palavras-chave:</h3>
                    {% for tag in tag_list %}
                        <a href={{ tag.get_absolute_url }}>{{ tag }}{% if not forloop.last %}, {% endif %}</a>
                    {% endfor %}
                    <br />
                {% endif %}
                {% if prize_list %}
                    <h3>Prêmio{{ prize_list|pluralize:"s" }}</h3>
                    {% for prize in prize_list %}
                        <img src="{{ MEDIA_URL }}images/star.png" id="star" alt="estrela" /> {{ prize.name }}<br/>
                    {% endfor %} 
                {% endif %}
                <h3>Resumo</h3>
                  {{ project.abstract }}
                <br /><br />
                {% if project.slug %}
                    <a href={% url blog_index_slug project_slug=project.slug %}>Diário de Bordo</a><br/>
                {% else %}
                    {% if project.slug %}
                    <a href={% url blog_index_slug project_slug=project.slug %}>Diário de Bordo</a><br/>
                    <a href={% url pl-gallery slug=project.slug %}>Galeria de fotos</a><br/>
                    {% else %}
                    <a href={% url blog_index edition=project.edition category=project.category code=project.code %}>Diário de Bordo</a><br/>
                    <a href={% url pl-project-gallery edition=project.edition category=project.category code=project.code %}>Galeria de fotos</a><br/>
                    {% endif %}
                {% endif %}
                <br/>
		</div>
    </div>
{% endblock %}

{% block columnB %}
    <div class="column" id="columnB">
		<div class="columnBhead">
            <h2>Recados</h2>
			<div class="clear">&nbsp;</div>
		</div>
		<div class="subcolumns">
			<div class="subcolumn" id="columnBleft">
                {% load comments %}
                {% get_comment_form for project as form %}
                <form action="{% comment_form_target %}" method="POST">
                    {% if user.is_anonymous %}
                        <div class="field">
                            <label for="id_name"><h3>Nome</h3></label>
                            {{ form.name }} {{ form.name.errors }}
                        </div>
                        <div class="field">
                            <label for="id_email"><h3>E-mail</h3></label>
                            {{ form.email }} {{ form.email.errors }}
                        </div>
                        <div class="field">
                            <label for="id_url"><h3>URL</h3></label>
                            {{ form.url }} {{ form.url.errors }}
                        </div>
                    {% endif %}
                    <div class="field">
                        <label for="id_comment"><h3>Texto</h3></label>
                        {{ form.comment }} {{ form.comment.errors }}
                    </div>
                    <br>
                     <p style="display:none;">
                         <label for="id_honeypot">Se você escrever algo aqui, seu recado será tratado como spam</label>
                        {{ form.honeypot }}
                    </p>
                    {{ form.content_type }}
                    {{ form.object_pk }}
                    {{ form.timestamp }}
                    {{ form.security_hash }}
                    <input type="hidden" name="next" value="{{ project.get_absolute_url }}" />
                    <input type="submit" value="Enviar recado" id="id_submit" />
                </form>
                <br><br>
                <h3>Recados recebidos</h3>
                <br>
                {% get_comment_list for project as comment_list %}
                {% if comment_list %}
                    <ul>
                        {% for comment in comment_list reversed %}
                            <li>
                            {% if comment.user.get_profile %}
	                            <a href="{{ comment.user.get_profile.get_absolute_url }}" class="label">{{ comment.user.get_profile.name }}</a>
                            {% else %} 
                                {% if comment.url %}
                                     <a href="{{ comment.url }}" class="label">{{ comment.user_name }}</a>
                                {% else %}
                                     {{ comment.user_name }}
                                {% endif %}
                            {% endif %}
                            </li>
                            <li> {{ comment.submit_date|date:"d/m/Y H:i" }}</li>
                            <li> {{ comment.comment }}</li>
                            <br>
                        {% endfor %}
                    </ul>
                {% else %}
                    <p>Não há recados recebidos.</p>
                {% endif %}
			    <div class="clear">&nbsp;</div>
	        </div>
        </div>
    </div>
{% endblock %}

templates/projects/project_list.html
{% extends "projects/base.html" %}

{% block header%}
    <h1>{{ block.super }} {{ title }}</h1> 
{% endblock %}

{% block content %}

    {% if project_list %}
        <ul>
        {% for project in project_list %}
            <li><a href="{{ project.get_absolute_url }}">{{ project.name }}</a></li>
        {% endfor %}
        </ul>
    {% else %}
        <p>Não há projetos cadastrados.</p>
    {% endif %}

{% endblock %}

templates/projects/projects_by_tag.html
{% extends "base.html" %}

{% block title%} | Projetos {% endblock %}

{% block header%}
    <h1>Projetos</h1>
{% endblock %}

{% block content %}

    <ul>
    {% for project in object_list %}
        <li><a href="{{ project.get_absolute_url }}">{{ project.name }}</a></li>
    {% endfor %}
    </ul>

{% endblock %}

templates/projects/projects_main.html
{% extends "base.html" %}

{% block title %} | Projetos {% endblock %}

{% block header %}
    <h1>Projetos</h1>
{% endblock %}

{% block content %}


    <h2>Projetos por categoria<h2>
    <br />
    <ul>
    {% for key, category in categories %}
        <li><a href="{% url projects_by_category key  %}">{{ category }}</a></li>
    {% endfor %}
    </ul>

    <br />

    <h2>Projetos por ano<h2>
    <br />
    <ul>
    {% for year in years reversed %}
        <li><a href="{% url projects_by_year year  %}">{{ year }}</a></li>
    {% endfor %}
    </ul>

    {% if user.is_authenticated %}
	<br />
        <h2>Crie o seu projeto<h2>
        <input type="button" onClick="parent.location='{% url projects_request_project  %}'" value="Novo projeto">
        <br /><br />
    {% endif %} 

{% endblock %}

templates/projects/request_project.html
{% extends "base.html" %}

{% block title%} | Solicitar Projeto{% endblock %}

{% block header%}
    <h1>Solicitar Projeto</h1>
{% endblock %}

{% block content %}
    Você tem certeza? <br/>

    <input type="button" onClick="parent.location='{% url projects_new_project %}'" value="Sim">
    <input type="button" onClick="parent.location='{{ visitor.get_absolute_url }}'" value="Não">

{% endblock %}