profiles/urls.py
"""
URLConf for Django user profile management.

Recommended usage is to use a call to ``include()`` in your project's
root URLConf to include this URLConf for any URL beginning with
'/profiles/'.

If the default behavior of the profile views is acceptable to you,
simply use a line like this in your root URLConf to set up the default
URLs for profiles::

    (r'^profiles/', include('profiles.urls')),

But if you'd like to customize the behavior (e.g., by passing extra
arguments to the various views) or split up the URLs, feel free to set
up your own URL patterns for these views instead. If you do, it's a
good idea to keep the name ``profiles_profile_detail`` for the pattern
which points to the ``profile_detail`` view, since several views use
``reverse()`` with that name to generate a default post-submission
redirect. If you don't use that name, remember to explicitly pass
``success_url`` to those views.

"""

from django.conf.urls.defaults import *

from profiles import views


urlpatterns = patterns('',
                       url(r'^create/$',
                           views.create_profile,
                           name='profiles_create_profile'),
                       url(r'^edit/$',
                           views.edit_profile,
                           name='profiles_edit_profile'),
                       url(r'^delete/$',
                           views.delete_profile,
                           name='profiles_delete_profile'),
                       url(r'^delete/confirm$',
                           views.delete_profile_confirm,
                           name='profiles_delete_profile_confirm'),
                       url(r'^(?P<username>\w+)/$',
                           views.profile_detail,
                           name='profiles_profile_detail'),
                       url(r'^$',
                           views.profile_list,
                           name='profiles_profile_list'),
                       )

tagging/urls.py
from django.conf.urls.defaults import *
from projects.models import Project
from tagging.models import Tag

urlpatterns = patterns('',
    url(
        r'^$',
        'django.views.generic.list_detail.object_list',
        { 'queryset': Tag.objects.all() }
    ),
    url(
        r'^(?P<tag>[-\w\s]+)/$',
        'tagging.views.tag_detail',
        name = 'tagging_tag_detail',
    ),
    url(
        r'^projects/(?P<tag>[-\w]+)/$',
        'tagging.views.tagged_object_list',
        { 'queryset_or_model': Project,
        'template_name': 'projects/projects_by_tag.html' }
    ),
)

urls.py
# -*- coding: utf-8 -*-
from django.conf.urls.defaults import *
from django.conf import settings

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    (r'^admin/doc/', include('django.contrib.admindocs.urls')),
    (r'^admin/(.*)', admin.site.root),
    (r'^accounts/', include('registration.urls')),
    (r'^articles/', include('articles.urls')),
    (r'^blog/', include('blog.urls')),
    (r'^comments/', include('django.contrib.comments.urls')),
    (r'^friends/', include('friends.urls')),
    (r'^institutions/', include('institutions.urls')),
    (r'^profiles/', include('profiles.urls')),
    (r'^projects/', include('projects.urls')),
    (r'^search/', include('search.urls')),
    (r'^tags/', include('tagging.urls')),
    (r'^messages/', include('messages.urls')),
    (r'^photologue/', include('photologue.urls')),
    (r'^stats/', include('status.urls')),
    (r'^$', include('home.urls')),
    (r'^media/(.*)$', 'django.views.static.serve',
     {'document_root': settings.MEDIA_ROOT}),
)

profile/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib import admin

GENDER_CHOICES = (
    ('M', 'Masculino'),
    ('F', 'Feminino'),
)

USER_TYPES = (
    ('A', 'Avaliador'),
    ('E', 'Equipe'),
    ('F', 'Finalista'),
    ('O', 'Orientador'),
    ('V', 'Visitante'),
)

class UserProfile(models.Model):
    """
    User class fields:

    username
    first_name
    last_name
    email
    password
    is_staff
    is_active
    is_superuser
    last_login
    date_joined
    """

    user = models.ForeignKey(User, unique=True)
    user_type = models.CharField(max_length=1, choices=USER_TYPES)

    city = models.CharField(max_length=100)
    state =  models.CharField(max_length=2)
    birthdate = models.DateField()
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES)

    mugshot = models.URLField()
    institution = models.CharField(max_length=100)

    def __unicode__(self):
        return self.user.username

    def get_absolute_url(self):
        return ('profiles_profile_detail', (), { 'username': self.user.username })
    get_absolute_url = models.permalink(get_absolute_url)

admin.site.register(UserProfile)

profiles/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.contrib.auth.models import User
from friends.utils import get_following_set
from django.contrib.localflavor.br.br_states import STATE_CHOICES
from institutions.models import Institution

GENDER_CHOICES = (
    (u'Masculino', u'Masculino'),
    (u'Feminino', u'Feminino'),
)

USER_TYPES = (
    (u'A', u'Avaliador'),
    (u'E', u'Equipe'),
    (u'F', u'Finalista'),
    (u'O', u'Orientador'),
    (u'V', u'Visitante'),
)

class UserProfile(models.Model):
    """
    User class fields:

    | username | first_name | last_name | email | password | is_staff |
    | is_active | is_superuser | last_login | date_joined |

    """

    user = models.ForeignKey(User, unique=True, blank=True, null=True, verbose_name='Usuário')
    user_type = models.CharField(max_length=1, choices=USER_TYPES, blank=True, default='V', verbose_name='Tipo de Usuário')
    name = models.CharField(max_length=255, verbose_name='Nome')

    city = models.CharField(max_length=100, blank=True, verbose_name='Cidade')
    state =  models.CharField(max_length=2, choices=STATE_CHOICES, blank=True, verbose_name='Estado')
    birthdate = models.DateField(null=True, blank=True, verbose_name='Data de Nascimento')
    gender = models.CharField(max_length=9, choices=GENDER_CHOICES, blank=True, verbose_name='Sexo')

    institution = models.ForeignKey(Institution, blank=True, null=True, verbose_name='Instituição')
    mugshot = models.ImageField(upload_to='uploads/', blank=True, verbose_name='Foto')
    is_active = models.BooleanField(default=True, verbose_name='Ativo?')

    def __unicode__(self):
        return self.name

    @models.permalink
    def get_absolute_url(self):
        try:    
            return ('profiles_profile_detail', (), { 'username': self.user.username })
        except:
            return ('index', (), {})

    class Meta:
        verbose_name='Perfil'
        verbose_name_plural='Perfis'

profile/forms.py
from django import forms
from profile.models import UserProfile
from django.contrib.auth.models import User

class ProfileForm(forms.ModelForm):

    class Meta:
        model = UserProfile
        exclude = ('user',)

class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email',)

profiles/forms.py
from django import forms
from profiles.models import UserProfile
from django.contrib.auth.models import User

class ProfileForm(forms.ModelForm):

    class Meta:
        model = UserProfile
        exclude = ('user', 'user_type', 'is_active',)

class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('email',)

profiles/views.py
"""
Views for creating, editing and viewing site-specific user profiles.

"""

from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist
from django.core.urlresolvers import reverse
from django.http import Http404
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.views.generic.list_detail import object_list
from django.contrib.auth import logout

from profiles import utils
from profiles.forms import ProfileForm
from profiles.forms import UserForm
from profiles.models import UserProfile

from friends import utils as friends_utils
from projects import utils as projects_utils

from friends.models import FriendLink

def create_profile(request, form_class=ProfileForm, success_url=None,
                   template_name='profiles/create_profile.html',
                   extra_context=None):
    """
    Create a profile for the current user, if one doesn't already
    exist.

    If the user already has a profile, as determined by
    ``request.user.get_profile()``, a redirect will be issued to the
    :view:`profiles.views.edit_profile` view. If no profile model has
    been specified in the ``AUTH_PROFILE_MODULE`` setting,
    ``django.contrib.auth.models.SiteProfileNotAvailable`` will be
    raised.

    **Optional arguments:**

    ``extra_context``
        A dictionary of variables to add to the template context. Any
        callable object in this dictionary will be called to produce
        the end result which appears in the context.

    ``form_class``
        The form class to use for validating and creating the user
        profile. This form class must define a method named
        ``save()``, implementing the same argument signature as the
        ``save()`` method of a standard Django ``ModelForm`` (this
        view will call ``save(commit=False)`` to obtain the profile
        object, and fill in the user before the final save). If the
        profile object includes many-to-many relations, the convention
        established by ``ModelForm`` of using a method named
        ``save_m2m()`` will be used, and so your form class should
        also define this method.

        If this argument is not supplied, this view will use a
        ``ModelForm`` automatically generated from the model specified
        by ``AUTH_PROFILE_MODULE``.

    ``success_url``
        The URL to redirect to after successful profile creation. If
        this argument is not supplied, this will default to the URL of
        :view:`profiles.views.profile_detail` for the newly-created
        profile object.

    ``template_name``
        The template to use when displaying the profile-creation
        form. If not supplied, this will default to
        :template:`profiles/create_profile.html`.

    **Context:**

    ``form``
        The profile-creation form.

    **Template:**

    ``template_name`` keyword argument, or
    :template:`profiles/create_profile.html`.

    """
    try:
        profile_obj = request.user.get_profile()
        return HttpResponseRedirect(reverse('profiles_edit_profile'))
    except ObjectDoesNotExist:
        pass

    #
    # We set up success_url here, rather than as the default value for
    # the argument. Trying to do it as the argument's default would
    # mean evaluating the call to reverse() at the time this module is
    # first imported, which introduces a circular dependency: to
    # perform the reverse lookup we need access to profiles/urls.py,
    # but profiles/urls.py in turn imports this module.
    #

    if success_url is None:
        success_url = reverse('profiles_profile_detail',
                              kwargs={ 'username': request.user.username })
    if form_class is None:
        form_class = utils.get_profile_form()

    if request.method == 'POST':
        profile_form = form_class(data=request.POST, files=request.FILES)
        user_form = UserForm(data=request.POST, files=request.FILES,
                             instance=request.user)
        if user_form.is_valid() and profile_form.is_valid():
            user_obj = user_form.save()

            profile_obj = profile_form.save(commit=False)
            profile_obj.user = request.user
            profile_obj.save()

            if hasattr(profile_form, 'save_m2m'):
                profile_form.save_m2m()
            return HttpResponseRedirect(success_url)
    else:
        user_form = UserForm(instance=request.user)
        profile_obj = UserProfile.objects.create(user=request.user)
        profile_form = form_class(instance=profile_obj)

    if extra_context is None:
        extra_context = {}
    context = RequestContext(request)
    for key, value in extra_context.items():
        context[key] = callable(value) and value() or value

    return render_to_response(template_name,
                              { 'user_form': user_form,
                               'profile_form': profile_form},
                              context_instance=context)
create_profile = login_required(create_profile)

def edit_profile(request, form_class=ProfileForm, success_url=None,
                 template_name='profiles/edit_profile.html',
                 extra_context=None):
    """
    Edit the current user's profile.

    If the user does not already have a profile (as determined by
    ``User.get_profile()``), a redirect will be issued to the
    :view:`profiles.views.create_profile` view; if no profile model
    has been specified in the ``AUTH_PROFILE_MODULE`` setting,
    ``django.contrib.auth.models.SiteProfileNotAvailable`` will be
    raised.

    **Optional arguments:**

    ``extra_context``
        A dictionary of variables to add to the template context. Any
        callable object in this dictionary will be called to produce
        the end result which appears in the context.

    ``form_class``
        The form class to use for validating and editing the user
        profile. This form class must operate similarly to a standard
        Django ``ModelForm`` in that it must accept an instance of the
        object to be edited as the keyword argument ``instance`` to
        its constructor, and it must implement a method named
        ``save()`` which will save the updates to the object. If this
        argument is not specified, this view will use a ``ModelForm``
        generated from the model specified in the
        ``AUTH_PROFILE_MODULE`` setting.

    ``success_url``
        The URL to redirect to following a successful edit. If not
        specified, this will default to the URL of
        :view:`profiles.views.profile_detail` for the profile object
        being edited.

    ``template_name``
        The template to use when displaying the profile-editing
        form. If not specified, this will default to
        :template:`profiles/edit_profile.html`.

    **Context:**

    ``form``
        The form for editing the profile.

    ``profile``
         The user's current profile.

    **Template:**

    ``template_name`` keyword argument or
    :template:`profiles/edit_profile.html`.

    """
    try:
        profile_obj = request.user.get_profile()
    except ObjectDoesNotExist:
        return HttpResponseRedirect(reverse('profiles_create_profile'))

    #
    # See the comment in create_profile() for discussion of why
    # success_url is set up here, rather than as a default value for
    # the argument.
    #

    if success_url is None:
        success_url = reverse('profiles_profile_detail',
                              kwargs={ 'username': request.user.username })
    if form_class is None:
        form_class = utils.get_profile_form()

    if request.method == 'POST':
        profile_form = form_class(data=request.POST, files=request.FILES, instance=profile_obj)
        user_form = UserForm(data=request.POST, files=request.FILES,
                             instance=request.user)

        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            return HttpResponseRedirect(success_url)
    else:
        user_form = UserForm(instance=request.user)
        profile_form = form_class(instance=profile_obj)

    if extra_context is None:
        extra_context = {}
    context = RequestContext(request)
    for key, value in extra_context.items():
        context[key] = callable(value) and value() or value

    return render_to_response(template_name,
                              { 'user_form': user_form,
                                'profile_form': profile_form,
                                'profile': profile_obj, },
                              context_instance=context)
edit_profile = login_required(edit_profile)

def profile_detail(request, username, public_profile_field=None,
                   template_name='profiles/profile_detail.html',
                   extra_context=None):
    """
    Detail view of a user's profile.

    If no profile model has been specified in the
    ``AUTH_PROFILE_MODULE`` setting,
    ``django.contrib.auth.models.SiteProfileNotAvailable`` will be
    raised.

    If the user has not yet created a profile, ``Http404`` will be
    raised.

    **Required arguments:**

    ``username``
        The username of the user whose profile is being displayed.

    **Optional arguments:**

    ``extra_context``
        A dictionary of variables to add to the template context. Any
        callable object in this dictionary will be called to produce
        the end result which appears in the context.

    ``public_profile_field``
        The name of a ``BooleanField`` on the profile model; if the
        value of that field on the user's profile is ``False``, the
        ``profile`` variable in the template will be ``None``. Use

templates/profiles/create_profile.html
{% extends "base.html" %}

{% block title%} | Criar Perfil{% endblock %}

{% block header%}
    <h1>Criar Perfil</h1>
{% endblock %}

{% block content %}

    {% if user_form.errors %}
        <p style="color: red;">
            Por favor, corrija o{{ user_form.errors|pluralize }} erro{{ user_form.errors|pluralize }} abaixo.
        </p>
    {% endif %}

    {% if profile_form.errors %}
        <p style="color: red;">
            Por favor, corrija o{{ profile_form.errors|pluralize }} erro{{ profile_form.errors|pluralize }} abaixo.
        </p>
    {% endif %}

    <form enctype="multipart/form-data" method="post" action="">
        <div class="field">
            <label for="id_email"><h2>E-mail</h2></label>
            {{ user_form.email }} {{ user_form.email.errors }}
        </div>
        <br>
        <div class="field">
            <label for="id_name"><h2>Nome</h2></label>
            {{ profile_form.name }} {{ profile_form.name.errors }}
        </div>
        <br>
        <div class="field">
            <label for="id_city"><h2>Cidade</h2></label>
            {{ profile_form.city }} {{ profile_form.city.errors }}
        </div>
        <br>
        <div class="field">
            <label for="id_state"><h2>Estado</h2></label>
            {{ profile_form.state }} {{ profile_form.state.errors }}
        </div>
        <br>
        <div class="field">
            <label for="id_bithdate"><h2>Data de Nascimento</h2></label>
            {{ profile_form.birthdate }} {{ profile_form.birthdate.errors }}
        </div>
        <br>
        <div class="field">
            <label for="id_gender"><h2>Sexo</h2></label>
            {{ profile_form.gender }} {{ profile_form.gender.errors }}
        </div>
        <br>
        <div class="field">
            <label for="id_institution"><h2>Instituição</h2></label>
            {{ profile_form.institution }} {{ profile_form.institution.errors }}
        </div>
        <br>
        <div class="field">
            <label for="id_mugshot"><h2>Foto</h2></label>
            {{ profile_form.mugshot }} {{ profile_form.mugshot.errors }}
        </div>
        <br><br>
        <input type="submit" value="Enviar">
    </form>
{% endblock %}

templates/profiles/delete_profile.html
{% extends "base.html" %}

{% block title%} | Apagar Perfil{% endblock %}

{% block header%}
    <h1>Apagar Perfil</h1>
{% endblock %}

{% block content %}
    Você tem certeza? <br/>

    <input type="button" onClick="parent.location='{% url profiles_delete_profile_confirm %}'" value="Sim">
    <input type="button" onClick="parent.location='{{ visitor.get_absolute_url }}'" value="Não">

{% endblock %}

templates/profiles/edit_profile.html
{% extends "base.html" %}

{% block title%} | Editar Perfil{% endblock %}

{% block header%}
    <h1>Editar Perfil</h1>
{% endblock %}

{% block content %}

    {% if user_form.errors %}
        <p style="color: red;">
            Por favor, corrija o{{ user_form.errors|pluralize }} erro{{ user_form.errors|pluralize }} abaixo.
        </p>
        <br>
    {% endif %}

    {% if profile_form.errors %}
        <p style="color: red;">
            Por favor, corrija o{{ profile_form.errors|pluralize }} erro{{ profile_form.errors|pluralize }} abaixo.
        </p>
        <br>
    {% endif %}

    <form enctype="multipart/form-data" method="post" action="">
        <div class="field">
            <label for="id_email"><h2>E-mail</h2></label>
            {{ user_form.email }} {{ user_form.email.errors }}
        </div>
        <br>
        <div class="field">
            <label for="id_name"><h2>Nome</h2></label>
            {{ profile_form.name }} {{ profile_form.name.errors }}
        </div>
        <br>
        <div class="field">
            <label for="id_city"><h2>Cidade</h2></label>
            {{ profile_form.city }} {{ profile_form.city.errors }}
        </div>
        <br>
        <div class="field">
            <label for="id_state"><h2>Estado</h2></label>
            {{ profile_form.state }} {{ profile_form.state.errors }}
        </div>
        <br>
        <div class="field">
            <label for="id_bithdate"><h2>Data de Nascimento</h2></label>
            {{ profile_form.birthdate }} {{ profile_form.birthdate.errors }}
        </div>
        <br>
        <div class="field">
            <label for="id_gender"><h2>Sexo</h2></label>
            {{ profile_form.gender }} {{ profile_form.gender.errors }}
        </div>
        <br>
        <div class="field">
            <label for="id_institution"><h2>Instituição</h2></label>
            {{ profile_form.institution }} {{ profile_form.institution.errors }}
        </div>
        <br>
        <div class="field">
            <label for="id_mugshot"><h2>Foto</h2></label>
            {{ profile_form.mugshot }} {{ profile_form.mugshot.errors }}
        </div>
        <br><br>
        <input type="submit" value="Enviar">
    </form>
{% endblock %}